services:
  flask_app:
    container_name: flask_app
    image: dockerhub-flask_live_app:1.0.0
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./app/templates:/app/templates
      - ./app/DataBase.db:/app/DataBase.db